### ISSUE TITLE
Добавить лицензию к материалам курса

### ISSUE THREAD

**Issue by simgislab** [nextgis/webgis_course#7]
что-нибудь типа CC-BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/legalcode#languages

или даже CC-BY-ND (у общих док такая лицензия и наверное с доками это имеет смысл)

лучше  в подвал

**Comment by drnextgis** [comment]
Поместил логотип и ссылку на лицензию в правый нижний угол.
